project:
  type: website
  output-dir: docs

website:
  title: "Kevin Valdivia"
#  site-url: https://yourwebsite.dev  # Add your site URL if applicable
  description: ""  # Add a description for the website
  navbar:
    right:
      - href: index.qmd
        text: Home
#      - href: about.qmd
#        text: About
      - text: "Essays"
        menu:
          - href: essays/mex_ine/electoral_reforms.qmd
            text: "Behind AMLO’s Electoral Reforms"
          - href: essays/mex_ed/mexican_education.qmd
            text: "The Mexican Education System"
          - href: essays/cfa_zone/cfa_zone.qmd
            text: "Economic Integration in Francophone Africa"
          - href: essays/westphalia/westphalia.qmd
            text: "Beyond Westphalia"
          - href: projects/peso/peso_doc.qmd
            text: "The Peso In Crisis"
      - text: "Projects"
        menu:
          - href: projects/the office/office_text_analysis.qmd
            text: "**Text Analysis:** *The Office*"
          - href: projects/simulation_study/permutation_experiment.qmd
            text: "**Permutation Analysis**: *Room Draw*"
          - href: projects/sql_mini_project/sql_project.qmd
            text: "**Graph Replication**: With SQL"
      - href: tidytuesday/tidytuesday.qmd
        text: "**Tidytuesday Adventures**"
  open-graph:
    locale: en_US
  comments:
    utterances:
      repo: yourusername/yourrepository  # Add your GitHub repo if using Utterances
  page-footer:
    left: "© Copyright 2024 Kevin Valdivia. Except where otherwise noted, all text and images licensed CC-BY-NC 4.0."

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
